{
    "name": "Real Estate",
    "summary": "Technical Training Module",
    "description": "The real state module is create base on the Odoo 16.0 documentation",
    "author": "Vauxoo",
    "license": "LGPL-3",
    "category": "Real Estate/Brokerage",
    "version": "16.0.1.0.0",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/estate_menus.xml",
        "data/property.type.csv",
        "views/property_views.xml",
        "views/property_type_views.xml",
        "views/property_tag_views.xml",
        "views/property_offer_views.xml",
        "views/res_users_views.xml",
        "report/property_offer_table_template.xml",
        "report/property_offer_template.xml",
        "report/res_users_property_template.xml",
        "report/res_users_property_report.xml",
        "report/property_offer_report.xml",
    ],
    "demo": ["demo/demo_data.xml"],
    "application": True,
    "installable": True,
}
